version: '3'
services:
  game-client:
    build:
      context: .
      dockerfile: ./game-client.dockerfile
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/Caddyfile
  game-server:
    build:
      context: .
      dockerfile: ./game-server.dockerfile
    ports:
     - 10001-10010:10001-10010
